version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: ${DB_HOST}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis # Aponta para o serviço redis
    networks:
      - service-cliptozip-network

  db:
    image: postgres:16.11-alpine
    container_name: cliptozip-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: cliptozip
      POSTGRES_PASSWORD: cl!pt0z!p
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "7575:5432"  # Externa:Interna
    networks:
      - service-cliptozip-network

  redis:
    image: redis:alpine
    container_name: cliptozip-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - service-cliptozip-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: cliptozip-redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - service-cliptozip-network

  prometheus:
    image: prom/prometheus:v2.40.5
    container_name: cliptozip-prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - service-cliptozip-network

  grafana:
    image: grafana/grafana:9.2.5
    container_name: cliptozip-grafana
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - service-cliptozip-network

networks:
  service-cliptozip-network:
    driver: bridge

volumes:
  postgres_data: {}
