spring.application.name=authsvc
server.port=3000

# PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${POSTGRES_URL}
spring.jpa.database=postgresql
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# JWT
security.jwt.secret=P$v7hR!a9K#zL@xQ*c2bE5gYfT4jN6mU1oW0sD3iR8yQ
security.jwt.expiration-seconds=3600
