{
 "title": "JVM (Micrometer)",
 "tags": [
  "jvm",
  "micrometer"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(up, job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(up{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Application Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "format": "reqps",
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"$job\"}[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Error Rate (5xx)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "format": "percent",
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"$job\", status=~\"5..\"}[1m])) / sum(rate(http_server_requests_seconds_count{job=\"$job\"}[1m])) * 100",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{job=\"$job\"}[5m])) by (le, uri))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Total Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$job\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Total Memory Committed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_committed_bytes{job=\"$job\"})",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Total Memory Max",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_max_bytes{job=\"$job\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area='heap', job=\"$job\"}) / sum(jvm_memory_max_bytes{area='heap', job=\"$job\"}) * 100",
     "legendFormat": "Heap"
    }
   ]
  },
  {
   "title": "Non-Heap",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area='nonheap', job=\"$job\"}) / sum(jvm_memory_max_bytes{area='nonheap', job=\"$job\"}) * 100",
     "legendFormat": "Non-Heap"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(process_cpu_usage{job=\"$job\"}) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 9 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{job=\"$job\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"$job\"}",
     "legendFormat": "{{id}}"
    },
    {
     "expr": "jvm_memory_committed_bytes{job=\"$job\"}",
     "legendFormat": "{{id}} committed"
    }
   ]
  },
  {
   "title": "GC Pauses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{job=\"$job\"}[1m])",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"$job\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_daemon_threads{job=\"$job\"}",
     "legendFormat": "Daemon"
    }
   ]
  },
  {
   "title": "Classloader",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{job=\"$job\"}",
     "legendFormat": "Loaded"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"$job\"}[1m])",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}