package com.cliptozip.authsvc.application.usecase;

import com.cliptozip.authsvc.adapter.in.rest.request.RegisterRequest;
import com.cliptozip.authsvc.application.exception.EmailAlreadyExistsException;
import com.cliptozip.authsvc.application.port.out.UserPersistencePort;
import com.cliptozip.authsvc.domain.model.User;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.crypto.password.PasswordEncoder;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class RegisterUseCaseTest {

    @Mock
    private UserPersistencePort userPersistencePort;

    @Mock
    private PasswordEncoder passwordEncoder;

    @InjectMocks
    private RegisterUseCase registerUseCase;

    private RegisterRequest registerRequest;

    @BeforeEach
    void setUp() {
        registerRequest = new RegisterRequest(
                "Test User",
                "test@example.com",
                "password123"
        );
    }

    @Test
    void whenRegisterWithNewEmail_shouldSucceed() {
        // Given
        when(userPersistencePort.existsByEmail(registerRequest.email())).thenReturn(false);
        when(passwordEncoder.encode(registerRequest.password())).thenReturn("hashedPassword");

        // When
        registerUseCase.register(registerRequest);

        // Then
        // Verify that a user was saved
        ArgumentCaptor<User> userCaptor = ArgumentCaptor.forClass(User.class);
        verify(userPersistencePort).save(userCaptor.capture());
        User savedUser = userCaptor.getValue();

        // Check the details of the saved user
        assertThat(savedUser.getName()).isEqualTo("Test User");
        assertThat(savedUser.getEmail()).isEqualTo("test@example.com");
        assertThat(savedUser.getPassswordHash()).isEqualTo("hashedPassword");
        assertThat(savedUser.getUserId()).isNull(); // ID is generated by the database
    }

    @Test
    void whenRegisterWithExistingEmail_shouldThrowEmailAlreadyExistsException() {
        // Given
        when(userPersistencePort.existsByEmail(registerRequest.email())).thenReturn(true);

        // When & Then
        EmailAlreadyExistsException exception = assertThrows(EmailAlreadyExistsException.class, () -> {
            registerUseCase.register(registerRequest);
        });

        assertThat(exception.getMessage()).isEqualTo("Email already registered: " + registerRequest.email());

        // Verify that no interaction with the password encoder or save method occurred
        verify(passwordEncoder, never()).encode(anyString());
        verify(userPersistencePort, never()).save(any(User.class));
    }
}
